"""initial

Revision ID: a8fece80ca07
Revises: 
Create Date: 2022-09-16 14:29:11.370606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fece80ca07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_details_email', table_name='user_details')
    op.drop_index('ix_user_details_id', table_name='user_details')
    op.drop_index('ix_user_details_name', table_name='user_details')
    op.drop_table('user_details')
    op.drop_index('ix_userdetails_email', table_name='userdetails')
    op.drop_index('ix_userdetails_id', table_name='userdetails')
    op.drop_index('ix_userdetails_name', table_name='userdetails')
    op.drop_table('userdetails')
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.drop_index('ix_users_age', table_name='users')
    op.drop_index('ix_users_location', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'location')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('location', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_location', 'users', ['location'], unique=False)
    op.create_index('ix_users_age', 'users', ['age'], unique=False)
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.create_table('userdetails',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_userdetails_name', 'userdetails', ['name'], unique=False)
    op.create_index('ix_userdetails_id', 'userdetails', ['id'], unique=False)
    op.create_index('ix_userdetails_email', 'userdetails', ['email'], unique=False)
    op.create_table('user_details',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_details_name', 'user_details', ['name'], unique=False)
    op.create_index('ix_user_details_id', 'user_details', ['id'], unique=False)
    op.create_index('ix_user_details_email', 'user_details', ['email'], unique=False)
    # ### end Alembic commands ###
